apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tactful-ai/on-prem.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace:  default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: false