persistence:
  enabled: true
  storageClass: "longhorn"
  accessModes:
    - ReadWriteMany
  size: 3Gi

replica:
  replicaCount: 1

  resources:
    requests:
      memory: "100Mi"
      cpu: "500m"
    limits:
      memory: "500Mi"
      cpu: "1"

auth:
  enabled: false
