---
- name: Configure Servers
  hosts: external_vms
  gather_facts: yes
  become: yes

  vars:
    docker_version: "5:23.0.6-1~ubuntu.20.04~focal"

  tasks:

# Disable the firewall
    - name: Disable UFW
      shell: ufw disable

# shutdown the swap
    - name: Turn off swap
      shell: swapoff -a



# Update sysctl settings for Kubernetes networking
    - name: Create sysctl directory
      file:
        path: /etc/sysctl.d
        state: directory
        mode: '0755'

    - name: Create Kubernetes sysctl configuration file
      file:
        path: /etc/sysctl.d/kubernetes.conf
        state: touch
        mode: '0644'

    - name: Configure Kernel Parameters
      lineinfile:
        dest: /etc/sysctl.d/kubernetes.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-ip6tables = 1"
        - "net.bridge.bridge-nf-call-iptables = 1"

    - name: Apply Kernel Parameters
      shell: sysctl --system


  # Install docker engine

    - name: Install Required Packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - open-iscsi
          - nfs-common
        state: present

    - name: Create Docker keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Remove existing Docker GPG key file if it exists
      shell: rm -f /etc/apt/keyrings/docker.gpg
      ignore_errors: yes

    - name: Download Docker GPG key
      shell: "curl -fSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=\"{{ ansible_architecture }}\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce={{ docker_version }}
          - docker-ce-cli={{ docker_version }}
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        state: present
