- name: Configure Servers
  hosts: external_vms
  gather_facts: yes
  become: yes

  tasks:

    - name: Set logging
      ufw:
        logging: 'on'


    - name: Allow Control Plane Node Ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 6443

    - name: Allow Kubelet API Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "tcp"
      loop:
        - 10250

    - name: Allow Kube-Scheduler Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "tcp"
      loop:
        - 10251

    - name: Allow Kube-Controller-Manager Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "tcp"
      loop:
        - 10252

    - name: Allow etcd Ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "any"
      loop:
        - 2379
        - 2380

    - name: Allow Flannel Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "udp"
      loop:
        - 8472

    - name: Allow HTTP API Server Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "tcp"
      loop:
        - 80

    - name: Allow HTTPS API Server Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "tcp"
      loop:
        - 443


    - name: Allow SSH
      ufw:
        rule: allow
        port: 22
        comment: "Allow SSH"

    # - name: Allow NodePort Services Ports
    #   ufw:
    #     rule: allow
    #     port: 30776:32767
    #     proto: "tcp"

    # - name: Enable UFW
    #   ufw:
    #     state: enabled
