---
- name: Configure Servers
  hosts: external_vms
  gather_facts: yes
  become: yes

  tasks:
    - name: Allow Control Plane Node Ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 6443

    - name: Allow Kubelet API Port
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 10250

    - name: Allow Kube-Scheduler Port
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 10251

    - name: Allow Kube-Controller-Manager Port
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 10252

    - name: Allow etcd Ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 2379
        - 2380

    - name: Allow Flannel Port
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 8472

    - name: Allow HTTP API Server Port
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 80

    - name: Allow HTTPS API Server Port
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 443

    # - name: Allow NodePort Services Ports
    #   iptables:
    #     chain: INPUT
    #     protocol: tcp
    #     destination_port: "{{ item }}"
    #     jump: ACCEPT
    #   with_sequence: start=30776 end=30867

    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present

    - name: Save the current iptables rules using iptables-persistent
      shell: iptables-save > /etc/iptables/rules.v4
