- name: Configure worker_node
  hosts: "worker_nodes,master_nodes"
  gather_facts: true
  become: true
  tasks:
    ####################### install the packges that can control the firewall with #######################
    - name: Stop the Firewalld service
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true
      when: (ansible_os_family == 'RedHat' or ansible_os_family ==  "Suse")
