---
- name: Install Jump Server Prerequisites
  hosts: local_device
  become: true
  vars:
    install_rke: false
    rke_version: "v1.4.9"
  tasks:
    - name: Update package cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Check if RKE is installed
      stat:
        path: /usr/local/bin/rke
      register: rke_installed
    - name: Download and Install RKE
      shell: |
        wget https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64
        chmod +x rke_linux-amd64
        sudo mv rke_linux-amd64 /usr/local/bin/rke
      when: not rke_installed.stat.exists and install_rke
    - name: Install curl (if not already installed)
      package:
        name: curl
        state: present
      when: ansible_os_family == 'Debian'
    - name: Install curl (if not already installed)
      yum:
        name: curl
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'
    - name: Run Helm installation script
      shell: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
    - name: Install sshpass (Ubuntu)
      apt:
        name: sshpass
        state: present
      when: ansible_os_family == 'Debian'
    - name: Install sshpass (Red Hat)
      yum:
        name: sshpass
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Upgrade all packages (Ubuntu)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == 'Debian'
    - name: Upgrade all packages (Red Hat)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
