- name: Configure worker_node
  hosts: master_nodes
  gather_facts: true
  become: true
  tasks:
  ####################### RKE2 PORTS Require #######################
    - name: Allow communication for worker nodes to master
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 9345
      when: rke_version == "rke2"

  ######################### K8S NODES PORTS #######################
    - name: Allow Control Plane Node Ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 6443
    - name: Allow etcd Ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 2379
        - 2380
    - name: Allow Kube-Scheduler Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 10251
    - name: Allow Kube-Controller-Manager Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 10252

  vars:
    network_plugin: canal
    rke_version: rke1
    load_balancer: metallb
