- name: Configure worker_node
  hosts: worker_nodes
  gather_facts: true
  become: true
  tasks:
    - name: Allow NodePort Services Ports
      ufw:
        rule: allow
        port: 30776:32767
        proto: tcp

  vars:
    network_plugin: canal
    rke_version: rke1
    load_balancer: metallb
