- name: Configure worker_node
  hosts: worker_nodes
  gather_facts: true
  become: true
  vars:
    network_plugin: canal
    rke_version: rke1
    load_balancer: metallb
    package_manager: "{{ 'apt' if ansible_os_family == 'Debian' else 'yum' }}"
  tasks:
    ####################### install the packges that can control the firewall with #######################
    - name: Install UFW package
      package:
        name: ufw
        state: present
      when: package_manager == 'apt'
    - name: Install firewalld package
      package:
        name: firewalld
        state: present
      when: ansible_os_family == 'RedHat' or ansible_os_family ==  "Suse"
    - name: Ensure Firewalld is started and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat' or ansible_os_family ==  "Suse"
    ####################### allow node ports #######################
    - name: Reload firewall
      command: firewall-cmd --reload
      when: ansible_os_family == 'RedHat' or ansible_os_family ==  "Suse"

