- name: Configure worker_node
  hosts: worker_nodes
  gather_facts: true
  become: true
  vars:
    network_plugin: canal
    rke_version: rke1
    load_balancer: metallb
    package_manager: "{{ 'apt' if ansible_os_family == 'Debian' else 'yum' }}"
  tasks:
    ####################### install the packges that can control the firewall with #######################
    - name: Install UFW package
      package:
        name: ufw
        state: present
      when: package_manager == 'apt' # For Ubuntu
    - name: Install firewalld package
      package:
        name: firewalld
        state: present
      when: package_manager == 'yum' # For Red Hat
    - name: Ensure Firewalld is started and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes
      when: package_manager == 'yum' # For Red Hat
    ####################### allow node ports #######################
    - name: Allow NodePort Services Ports
      ufw:
        rule: allow
        port: 30776:32767
        proto: tcp
      when: package_manager == "apt" # FOR UBUNTU
    - name: Allow NodePort Services Ports
      firewalld:
        port: 30000-32767/tcp
        permanent: yes
        state: enabled
      when: package_manager == 'yum' # For Red Hat
    - name: Reload firewall
      command: firewall-cmd --reload
      when: package_manager == 'yum' # For Red Hat

